#!/usr/bin/env python3
"""
DOCX Report Generator for Prompt Research Orchestrator

Generates professionally formatted DOCX reports from workflow state data.

Usage:
    python generate_docx.py --workflow-state <path> --output <path>
"""

import json
import argparse
from datetime import datetime
from pathlib import Path

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
except ImportError:
    print("Error: python-docx not installed. Run: pip install python-docx")
    exit(1)


def load_workflow_state(path: str) -> dict:
    """Load workflow state from JSON file."""
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def create_document() -> Document:
    """Create a new document with default styles."""
    doc = Document()
    
    # Set default font
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)
    
    return doc


def add_title_page(doc: Document, data: dict):
    """Add title page to document."""
    # Title
    title = doc.add_paragraph()
    title_run = title.add_run("Prompt Engineering Framework\nComparison Report")
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph()
    
    # Frameworks compared
    frameworks = data.get('request', {}).get('frameworks_to_compare', [])
    if frameworks:
        frameworks_para = doc.add_paragraph()
        frameworks_run = frameworks_para.add_run(f"Comparing: {' vs '.join(frameworks)}")
        frameworks_run.font.size = Pt(14)
        frameworks_run.font.italic = True
        frameworks_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph()
    
    # Date
    date_para = doc.add_paragraph()
    date_run = date_para.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    date_run.font.size = Pt(12)
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Generated by
    gen_para = doc.add_paragraph()
    gen_run = gen_para.add_run("Generated by: Prompt Research Orchestrator")
    gen_run.font.size = Pt(10)
    gen_run.font.italic = True
    gen_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Page break
    doc.add_page_break()


def add_heading(doc: Document, text: str, level: int = 1):
    """Add a heading to the document."""
    heading = doc.add_heading(text, level=level)
    return heading


def add_paragraph(doc: Document, text: str, bold: bool = False):
    """Add a paragraph to the document."""
    para = doc.add_paragraph()
    run = para.add_run(text)
    if bold:
        run.font.bold = True
    return para


def add_table(doc: Document, headers: list, rows: list):
    """Add a table to the document."""
    table = doc.add_table(rows=len(rows) + 1, cols=len(headers))
    table.style = 'Table Grid'
    
    # Header row
    header_row = table.rows[0]
    for i, header in enumerate(headers):
        cell = header_row.cells[i]
        cell.text = header
        cell.paragraphs[0].runs[0].font.bold = True
        shading = OxmlElement('w:shd')
        shading.set(qn('w:fill'), 'D9D9D9')
        cell._tc.get_or_add_tcPr().append(shading)
    
    # Data rows
    for i, row_data in enumerate(rows):
        row = table.rows[i + 1]
        for j, cell_data in enumerate(row_data):
            row.cells[j].text = str(cell_data)
    
    return table


def add_executive_summary(doc: Document, data: dict):
    """Add executive summary section."""
    add_heading(doc, "Executive Summary", level=1)
    
    frameworks = data.get('request', {}).get('frameworks_to_compare', [])
    analysis = data.get('analysis_artifacts', {})
    
    # Key findings
    add_heading(doc, "Key Findings", level=2)
    
    pros_cons = analysis.get('comparison_tables', {}).get('pros_cons', {})
    for framework, details in pros_cons.items():
        pros = details.get('pros', [])
        if pros:
            add_paragraph(doc, f"{framework} strengths:", bold=True)
            for pro in pros[:3]:
                add_paragraph(doc, f"• {pro}")
    
    doc.add_paragraph()
    
    # Quick comparison
    add_heading(doc, "Quick Comparison", level=2)
    
    metrics = analysis.get('metrics', {})
    ease_of_use = metrics.get('ease_of_use', {})
    scalability = metrics.get('scalability', {})
    
    if ease_of_use:
        headers = ['Framework', 'Ease of Use', 'Scalability']
        rows = []
        for fw in frameworks:
            rows.append([
                fw,
                f"{ease_of_use.get(fw, 'N/A')}/10",
                scalability.get(fw, 'N/A')
            ])
        add_table(doc, headers, rows)
    
    doc.add_page_break()


def add_framework_descriptions(doc: Document, data: dict):
    """Add framework descriptions section."""
    add_heading(doc, "Framework Descriptions", level=1)
    
    framework_data = data.get('research_artifacts', {}).get('framework_data', {})
    
    for fw_name, fw_data in framework_data.items():
        add_heading(doc, fw_name.replace('_', ' ').title(), level=2)
        
        # Description
        description = fw_data.get('description', 'No description available.')
        add_paragraph(doc, description)
        
        # Core mechanism
        mechanism = fw_data.get('core_mechanism', '')
        if mechanism:
            add_paragraph(doc, "Core Mechanism:", bold=True)
            add_paragraph(doc, mechanism)
        
        # Thinking process
        thinking = fw_data.get('thinking_process', '')
        if thinking:
            add_paragraph(doc, "LLM Thinking Process:", bold=True)
            add_paragraph(doc, thinking)
        
        doc.add_paragraph()


def add_comparison_tables(doc: Document, data: dict):
    """Add comparison tables section."""
    add_heading(doc, "Comparison Tables", level=1)
    
    analysis = data.get('analysis_artifacts', {})
    pros_cons = analysis.get('comparison_tables', {}).get('pros_cons', {})
    
    # Pros/Cons Table
    add_heading(doc, "Pros and Cons", level=2)
    
    if pros_cons:
        headers = ['Aspect', *list(pros_cons.keys())]
        rows = []
        
        # Pros row
        pros_row = ['Pros']
        for fw, details in pros_cons.items():
            pros = details.get('pros', [])
            pros_text = '\n'.join([f"• {p}" for p in pros[:3]])
            pros_row.append(pros_text)
        rows.append(pros_row)
        
        # Cons row
        cons_row = ['Cons']
        for fw, details in pros_cons.items():
            cons = details.get('cons', [])
            cons_text = '\n'.join([f"• {c}" for c in cons[:3]])
            cons_row.append(cons_text)
        rows.append(cons_row)
        
        add_table(doc, headers, rows)
    
    doc.add_paragraph()
    
    # Metrics comparison
    add_heading(doc, "Metrics Comparison", level=2)
    
    metrics = analysis.get('metrics', {})
    frameworks = list(pros_cons.keys())
    
    if metrics and frameworks:
        headers = ['Metric', *frameworks]
        rows = []
        
        # Ease of Use
        if 'ease_of_use' in metrics:
            row = ['Ease of Use (1-10)']
            for fw in frameworks:
                score = metrics['ease_of_use'].get(fw, 'N/A')
                row.append(str(score))
            rows.append(row)
        
        # Scalability
        if 'scalability' in metrics:
            row = ['Scalability']
            for fw in frameworks:
                scale = metrics['scalability'].get(fw, 'N/A')
                row.append(scale)
            rows.append(row)
        
        # Compatibility
        if 'compatibility' in metrics:
            for platform in ['claude', 'grok']:
                row = [f'{platform.title()} Compatibility']
                for fw in frameworks:
                    compat = metrics['compatibility'].get(fw, {}).get(platform, 'N/A')
                    row.append(compat)
                rows.append(row)
        
        if rows:
            add_table(doc, headers, rows)
    
    doc.add_page_break()


def add_references(doc: Document, data: dict):
    """Add references section."""
    add_heading(doc, "References", level=1)
    
    sources = data.get('research_artifacts', {}).get('sources', [])
    deliverables = data.get('deliverables', {})
    citations = deliverables.get('citations', [])
    
    # Use citations if available, otherwise use sources
    if citations:
        for citation in citations:
            apa = citation.get('apa_format', '')
            if apa:
                para = doc.add_paragraph()
                para.add_run(apa)
                para.paragraph_format.left_indent = Inches(0.5)
                para.paragraph_format.first_line_indent = Inches(-0.5)
    elif sources:
        for source in sources:
            title = source.get('title', 'Unknown')
            url = source.get('url', '')
            accessed = source.get('accessed', '')
            
            ref_text = f"{title}"
            if url:
                ref_text += f"\nURL: {url}"
            if accessed:
                ref_text += f" Accessed: {accessed}"
            
            para = doc.add_paragraph()
            para.add_run(ref_text)
            para.paragraph_format.left_indent = Inches(0.5)
            para.paragraph_format.first_line_indent = Inches(-0.5)


def generate_report(workflow_state_path: str, output_path: str) -> str:
    """
    Generate DOCX report from workflow state.
    
    Args:
        workflow_state_path: Path to workflow_state.json
        output_path: Path for output .docx file
    
    Returns:
        Path to generated DOCX file
    """
    # Load data
    data = load_workflow_state(workflow_state_path)
    
    # Create document
    doc = create_document()
    
    # Add sections
    add_title_page(doc, data)
    add_executive_summary(doc, data)
    add_framework_descriptions(doc, data)
    add_comparison_tables(doc, data)
    add_references(doc, data)
    
    # Save document
    doc.save(output_path)
    
    return output_path


def main():
    parser = argparse.ArgumentParser(description='Generate DOCX report from workflow state')
    parser.add_argument('--workflow-state', required=True, help='Path to workflow_state.json')
    parser.add_argument('--output', required=True, help='Path for output .docx file')
    
    args = parser.parse_args()
    
    output_path = generate_report(args.workflow_state, args.output)
    print(f"Report generated: {output_path}")


if __name__ == '__main__':
    main()